fix: Ensure junit reporter is allowed to complete
palantir/godel-test-plugin pull request #94
Opened 2021-06-22 20:13 UTC by bmoylan

2021-06-22 22:07 UTC, tabboud approved these changes
👍

2021-06-22 22:10 UTC, nmiyake requested changes

2021-06-22 22:10 UTC, nmiyake commented on testplugin/test.go
> +			_, _ = fmt.Fprintf(stdout, "JUnit reporter failed: %v: %v\n", junitOutputCmd.Args, err)
Previously, if this `err` was non-nil, it would be returned from this function, but this changes the behavior so that it is no longer the case. Is this intentional? I understand not returning the error if another error already occurred, but if this is the only error then it seems like it should be returned from the function.

2021-06-23 14:30 UTC, bmoylan commented on testplugin/test.go
> +			_, _ = fmt.Fprintf(stdout, "JUnit reporter failed: %v: %v\n", junitOutputCmd.Args, err)
Yeah we can do that instead. lt actually was intentional as I was thinking that if there were no failing packages, we shouldn't care about the tooling failing, but thinking more I don't think we want a fleet of these things logging into CI nobody looks at. Went ahead and pushed an update.

2021-06-23 16:28 UTC, nmiyake requested changes
Thanks! Implementation looks good, but some feedback on content of changelog for release notes.

2021-06-23 16:28 UTC, nmiyake commented on changelog/@unreleased/pr-94.v2.yml
> +  description: Ensure junit reporter is allowed to complete
Can you expand this description a bit more so that the observable behavior that was fixed is clearer in the release notes? Something like "Fixes race condition where plugin could exit before JUnit reporter completed. Prior to this fix, running the test plugin with the `--junit` flag would sometimes not produce the JUnit test report if a test failed." (doesn't have to be this exact wording/not even sure if this is right, but just illustration of level of explanation that I think would be helpful/decipherable later when reading through release notes only)

2021-06-23 16:33 UTC, bmoylan commented on changelog/@unreleased/pr-94.v2.yml
> +  description: Ensure junit reporter is allowed to complete
no problem, updated!

2021-06-23 16:42 UTC, nmiyake requested changes
Sorry, last thing (the example text I provided has the wrong flag name, so should be corrected). Will approve and merge once that's fixed!

2021-06-23 16:42 UTC, nmiyake commented on changelog/@unreleased/pr-94.v2.yml
> +    Prior to this fix, running the test plugin with the --junit flag would sometimes not produce the JUnit test report if a test failed.
Sorry, I wrote my example without actually doing the research -- the flag is actually `--junit-output`, so let's update this to use that.

2021-06-23 16:46 UTC, bmoylan commented on changelog/@unreleased/pr-94.v2.yml
> +    Prior to this fix, running the test plugin with the --junit flag would sometimes not produce the JUnit test report if a test failed.
done!

2021-06-23 16:48 UTC, nmiyake approved these changes
Thanks for the fix!

2021-06-23 16:48 UTC, merged

2021-06-23 16:48 UTC, svc-autorelease commented
Released [1.8.0](https://github.com/palantir/godel-test-plugin/releases/tag/v1.8.0)